# Bibliotecas

## 1 Numpy

### 1.1 Arrays

Arrays são vetores ou matrizes (dependendo da dimensão), que suportam dados de um único tipo, diferentemente de listas. Eles são a unidade básica do pacote numpy, que é uma biblioteca poderosa para cálculos numéricos e matriciais.

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [2]:
a.dtype

dtype('int32')

In [3]:
a.shape

(5,)

In [4]:
b = np.array([[1.5, 2, 3], [5, 5, 6], [7, 8, 9]])
b

array([[1.5, 2. , 3. ],
       [5. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [5]:
b.dtype

dtype('float64')

In [6]:
b.shape

(3, 3)

### 1.2 Inicialização

Podemos inicializar os arrays de forma mais automática, usando algumas funções:

In [7]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.linspace( 0, 2, 9)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
b = np.zeros( (2,2) )
b

array([[0., 0.],
       [0., 0.]])

In [10]:
b = np.ones( (3,4), dtype=complex)
b

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [11]:
c = np.arange(10000)
c

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [12]:
c.reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

### 1.3 Operações Básicas

In [13]:
a = np.array([10, 20, 30, 40])
b = np.ones( 4 )
a+b

array([11., 21., 31., 41.])

In [14]:
a*2

array([20, 40, 60, 80])

In [15]:
a**2

array([ 100,  400,  900, 1600], dtype=int32)

In [16]:
5*np.sin(a)

array([-2.72010555,  4.56472625, -4.94015812,  3.7255658 ])

In [17]:
a < 30

array([ True,  True, False, False])

In [18]:
a[a < 30]

array([10, 20])

Nas operações matriciais, o operador * faz a multiplicação elemento a elemento.

In [19]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
A * B

array([[2, 0],
       [0, 4]])

O operador @ faz a multiplicação matricial.

In [20]:
A @ B

array([[5, 4],
       [3, 4]])

O método **dot** faz a multiplicação matricial de A por B.

In [21]:
A.dot(B)

array([[5, 4],
       [3, 4]])

### 1.4 Funções e Métodos

In [29]:
np.exp(1)

2.718281828459045

In [23]:
np.sqrt([16,25,36])

array([4., 5., 6.])

In [24]:
s = np.random.random( (3,5) )
s

array([[0.05272236, 0.36741613, 0.73996459, 0.2594056 , 0.22956865],
       [0.25507074, 0.46589706, 0.01894638, 0.67840388, 0.10201618],
       [0.84788065, 0.02326221, 0.89858739, 0.92990781, 0.66036056]])

In [27]:
s.std()

0.32082472825290304

In [28]:
s.mean(axis=1)

array([0.32981547, 0.30406685, 0.67199972])